import carMechanicImg from '../../images/engineer-4941341_1280.jpg';
import carElectronicImg from '../../images/diagnostics-4483859_1280.jpg';
import carTiresImg from '../../images/benjamin-brunner-K3cjUOMmMhc-unsplash.jpg';
import carDiagnosticImg from '../../images/engineer-4941347_1280.jpg';
import carClimaImg from '../../images/vehicle-3872550_1280.jpg';
import carOilImg from '../../images/oil-3979023_1280.jpg';
const servicesData = [
	{
		title: 'Mechanika samochodowa',
		description:
			'Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.',
		imagePath: carMechanicImg,
		altText: 'Kobieta diagnozująca samochód za pomocą laptopa',
	},
	{
		title: 'Elektronika',
		description:
			'Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.',
		imagePath: carElectronicImg,
    altText: 'Miernik samochodowy'
	},
	{
		title: 'Wulkanizacja',
		description:
			'Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.',
		imagePath: carTiresImg,
    altText: 'Wymiana koła samochodowego. Mężczyzna odkręca śruby'
	},
	{
		title: 'Diagnostyka komputerowa',
		description:
			'Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.',
		imagePath: carDiagnosticImg,
    altText: 'Kobieta jest w laboratorium samochodowym i przegląda wykresy na laptopie'
	},
	{
		title: 'Serwis klimatyzacji',
		description:
			'Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.',
		imagePath: carClimaImg,
    altText: 'Wywietrzniki w samochodzie'
	},
	{
		title: 'Wymiana oleju',
		description:
			'Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.Tempor nec feugiat nisl pretium fusce id velit ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibu ornare suspendisse sed nisi lacus sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus ataugue eget arcu dictum varius duis at consectetur lorem donec massapien faucibus et molestie ac feugiat sed lectus vestibulum mattiullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget.',
		imagePath: carOilImg,
    altText: 'Sprawdzanie poziomu oleju'
	},
	// ... Dodaj pozostałe usługi
];

export default servicesData;
